# Generated by Django 2.1.7 on 2019-05-30 17:07

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('item_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name_in_admin', models.CharField(default='', max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(upload_to=application.models.image_folder)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Мужчинам', 'Мужчины'), ('Женщинам', 'Женщины'), ('Мальчикам', 'Мальчики'), ('Девочкам', 'Девочки')], max_length=15, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('size', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to=application.models.image_folder)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.Brand')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='application.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('buying_type', models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default='Самовывоз', max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Выполняеться', 'Выполняеться'), ('Оплачен', 'Оплачен')], default='Принят в обработку', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('items', models.ManyToManyField(to='application.Cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='customer_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.CustomerCategory'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='application.CartItem'),
        ),
    ]
