# Generated by Django 2.1.7 on 2019-04-13 14:21

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Мужчинам', 'Мужчины'), ('Женщинам', 'Женщины'), ('Мальчикам', 'Мальчики'), ('Девочкам', 'Девочки')], max_length=15, unique=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('size', models.CharField(max_length=30)),
                ('material', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(upload_to=application.models.image_folder)),
                ('available', models.BooleanField(default=True)),
                ('cust_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CustomerCategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='customer_category',
            field=models.ManyToManyField(to='application.CustomerCategory'),
        ),
    ]
