# Generated by Django 2.1.7 on 2019-04-14 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190414_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='customer_category',
        ),
        migrations.AddField(
            model_name='category',
            name='customer_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='application.CustomerCategory'),
        ),
    ]
