# Generated by Django 2.1.7 on 2019-04-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190414_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='name_in_admin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
