# Generated by Django 2.1.7 on 2019-04-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_category_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cust_category',
        ),
    ]
